server:
  port: 10001

mina-port: 7020

spring:
  datasource:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:

mybatis-plus:
  type-aliases-package: com.ccssoft.cloudmessagemachine.entity
  mapper-locations: classpath:mybatis-mappers/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0 #逻辑删除
      logic-not-delete-value: 1 #逻辑未删除
