server:
  port: 12001
spring:
  application:
    name: airspace-server
  datasource:
    url: jdbc:mysql://183.56.219.211:33066/uav_cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    port: 16379
    host: 183.56.219.211
    timeout: 30000
    database: 1
    jedis:
      pool:
        min-idle: 10000
  session:
    store-type: redis
  cloud:
    sentinel:
      transport:
        dashboard: 183.56.219.211:8858
        port: 8719
      datasource:
        ds:
          nacos:
            server-add: 183.56.219.211:8848
            dataId: airspace-nacos
            group: DEFAULT_GROUP
            data-type: json
            rule-type: flow

mybatis-plus:
  type-aliases-package: com.ccssoft.cloudcommon.entity
  mapper-locations: classpath:mybatis-mappers/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0 #逻辑删除(默认为1)
      logic-not-delete-value: 1 #逻辑未删除(默认为0)

#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #默认的控制台输出

bloom:
  filter:
    expectedInsertions: 1000
    fpp: 0.001F
service-url:
  nacos-user-service:

#激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true