server:
  port: 8001
spring:
  application:
    name: admin-server
  datasource:
    hikari:
      maximum-pool-size: 20
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:
  redis:
    port: 16379
    host:
    timeout: 30000
    database: 0
    jedis:
      pool:
        min-idle: 10000
  session:
    store-type: redis


mybatis-plus:
  type-aliases-package: com.ccssoft.cloudcommon.entity
  mapper-locations: classpath:mybatis-mappers/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0 #逻辑删除(默认为1)
      logic-not-delete-value: 1 #逻辑未删除(默认为0)

#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #默认的控制台输出

bloom:
  filter:
    expectedInsertions: 1000
    fpp: 0.001F
